import Foundation

public struct MathBioDataset {
    public static var rawData:[String:[String]] = [
        "Math":[
            "A right circular cone is shown in the figure. Point A is the vertex of the cone and point B lies on the circumference of the base of the cone. The cone has a height of 24 units and a diameter of 20 units. What is the distance from point A to point B?", "The speed of an object is defined as the change in distance divided by the change in time. Information about objects A, B, C, and D are shown. Objects C and D both have constant speed. Based on the information given, rank the object names in order from greatest speed to least speed.", "How many beads did Damian and Trish each receive?", "Find the value of p.", "solve for x", "find x"],
        "Biology":[
            "What is cell theory?", "Are there living organisms without cell?", "What is the importance of proteins for living organisms?", "How many amino acids are known to form proteins in living organisms?", "What are the main types of lipids?", "What is the molecular structure of glycerol? To which organic functional group does this substance belong", "Are any bacteria made of more than one cell?"]]
    
    public static var wordOccurCount:[String:[String:Int]] =  ["main": ["Biology": 1], "cone": ["Math": 4], "value": ["Math": 1], "20": ["Math": 1], "substance": ["Biology": 1], "organisms": ["Biology": 3], "are": ["Math": 1, "Biology": 2], "each": ["Math": 1], "lipids": ["Biology": 1], "which": ["Biology": 1], "What": ["Math": 1, "Biology": 4], "Objects": ["Math": 1], "and": ["Math": 5], "speed": ["Math": 4], "change": ["Math": 2], "rank": ["Math": 1], "To": ["Biology": 1], "does": ["Biology": 1], "diameter": ["Math": 1], "object": ["Math": 2], "constant": ["Math": 1], "circular": ["Math": 1], "B": ["Math": 3], "amino": ["Biology": 1], "p.": ["Math": 1], "height": ["Math": 1], "theory": ["Biology": 1], "Point": ["Math": 1], "from": ["Math": 2], "point": ["Math": 3], "receive": ["Math": 1], "group": ["Biology": 1], "of": ["Math": 7, "Biology": 3], "on": ["Math": 2], "an": ["Math": 1], "D": ["Math": 2], "have": ["Math": 1], "importance": ["Biology": 1], "The": ["Math": 2], "distance": ["Math": 2], "molecular": ["Biology": 1], "the": ["Math": 12, "Biology": 3], "base": ["Math": 1], "How": ["Math": 1, "Biology": 1], "known": ["Biology": 1], "for": ["Math": 1, "Biology": 1], "is": ["Math": 4, "Biology": 3], "functional": ["Biology": 1], "beads": ["Math": 1], "many": ["Math": 1, "Biology": 1], "cells": ["Biology": 1], "right": ["Math": 1], "divided": ["Math": 1], "cell": ["Biology": 1], "in": ["Math": 4, "Biology": 1], "Information": ["Math": 1], "Trish": ["Math": 1], "a": ["Math": 2], "belong": ["Biology": 1], "find": ["Math": 1], "figure": ["Math": 1], "there": ["Biology": 1], "x": ["Math": 2], "vertex": ["Math": 1], "to": ["Math": 2, "Biology": 1], "given": ["Math": 1], "solve": ["Math": 1], "A": ["Math": 4], "C": ["Math": 2], "names": ["Math": 1], "Based": ["Math": 1], "time": ["Math": 1], "least": ["Math": 1], "Find": ["Math": 1], "units": ["Math": 2], "as": ["Math": 1], "objects": ["Math": 1], "has": ["Math": 1], "lies": ["Math": 1], "order": ["Math": 1], "Are": ["Biology": 1], "both": ["Math": 1], "organic": ["Biology": 1], "structure": ["Biology": 1], "proteins": ["Biology": 2], "shown": ["Math": 2], "without": ["Biology": 1], "acids": ["Biology": 1], "greatest": ["Math": 1], "information": ["Math": 1], "form": ["Biology": 1], "this": ["Biology": 1], "24": ["Math": 1], "by": ["Math": 1], "glycerol": ["Biology": 1], "types": ["Biology": 1], "did": ["Math": 1], "living": ["Biology": 3], "circumference": ["Math": 1], "about": ["Math": 1], "defined": ["Math": 1], "Damian": ["Math": 1]]

    
    public static var typeOccurCount:[String: Int] = ["Math": 6, "Biology": 6]
    
    public static var totalTeachingCount = 12
    public static var totalWordCount = 102
}

